CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "secure_id" UUID UNIQUE NOT NULL DEFAULT (gen_random_uuid()),
  "username" varchar UNIQUE,
  "email" varchar UNIQUE,
  "phone_number" varchar UNIQUE,
  "password" varchar,
  "email_verified_at" timestamptz,
  "name" varchar NOT NULL,
  "region_code" int,
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()',
  "deleted_at" timestamptz
);